apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofisy-deployment
spec:
  template:
    metadata:
      name: ofisy-app
      labels:
        app: ofisy-app
    spec:
      containers:
        - name: ofisy-app
          image: ofisy-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ofisy-config
            - secretRef:
                name: ofisy-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
  selector:
    matchLabels:
      app: ofisy-app
