apiVersion: v1
kind: Secret
metadata:
  name: ofisy-secret
type: Opaque
stringData:
  POSTGRES_USER: ofisy_user
  POSTGRES_PASSWORD: ofisy_pass
  JWT_SECRET: super_secret_local_jwt_token_for_ofisy_app_fase_2
