spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ofisydb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  config:
    import: optional:file:.env[.properties]
management:
    endpoints:
      web:
        exposure:
          include: health
security:
  public-paths:
    - /api/v1/login
    - /api/v1/customers
    - /swagger-ui/**
    - /swagger-ui.html
    - /v3/api-docs/**
logging:
  level:
    org.flywaydb: DEBUG
jwt:
  admin-password: ${ADMIN_PASSWORD}
  admin-login: ${ADMIN_LOGIN}
  secret: ${JWT_SECRET}
  expiration: 86400000