apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofisy-deployment
spec:
  template:
    metadata:
      name: ofisy-app
      labels:
        app: ofisy-app
        tags.datadoghq.com/service: ofisy-api
      annotations:
        ad.datadoghq.com/ofisy-app.checks: |
          {
            "http_check": {
              "instances": [
                {
                  "name": "ofisy-api",
                  "url": "http://%%host%%:8080/actuator/health"
                }
              ]
            }
          }
    spec:
      containers:
        - name: ofisy-app
          image: <ECR_REPOSITORY_URL>:<IMAGE_TAG>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ofisy-config
            - secretRef:
                name: ofisy-secret
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
  selector:
    matchLabels:
      app: ofisy-app
