package br.com.ofisy.application.notification;

import br.com.ofisy.application.notification.dto.NotificationRequestDTO;
import br.com.ofisy.application.notification.dto.NotificationResponseDTO;
import br.com.ofisy.domain.notification.Notification;
import br.com.ofisy.domain.notification.NotificationRepository;
import br.com.ofisy.domain.stock.Stock;
import br.com.ofisy.domain.stock.StockRepository;
import net.jqwik.api.*;
import net.jqwik.api.Combinators;
import org.mockito.Mockito;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

// Feature: notification-stock-monitor, Propriedade 1: listAllReturnsAllNotificationsOrdered
// Feature: notification-stock-monitor, Propriedade 2: listUnreadFiltersCorrectly
// Feature: notification-stock-monitor, Propriedade 3: createNotificationRoundTrip
// Feature: notification-stock-monitor, Propriedade 5: markAsReadIsIdempotent
// Feature: notification-stock-monitor, Propriedade 7: timestampsAreSetCorrectly
class NotificationServicePropertyTest {

    private final NotificationRepository notificationRepository = Mockito.mock(NotificationRepository.class);
    private final StockRepository stockRepository = Mockito.mock(StockRepository.class);
    private final MockNotificationSender mockNotificationSender = Mockito.mock(MockNotificationSender.class);
    private final NotificationService notificationService =
            new NotificationService(notificationRepository, stockRepository, mockNotificationSender);

    /**
     * Propriedade 1: Listagem retorna todas as notificações com campos obrigatórios
     * Valida: Requisitos 1.1, 1.2
     */
    @Property(tries = 100)
    void listAllReturnsAllNotificationsOrdered(
            @ForAll("notificationLists") List<Notification> notifications
    ) {
        // Arrange
        when(notificationRepository.findAll()).thenReturn(notifications);

        // Act
        List<NotificationResponseDTO> result = notificationService.listAll();

        // Assert
        assertThat(result).hasSize(notifications.size());
        for (NotificationResponseDTO dto : result) {
            assertThat(dto.stockId()).isNotNull();
            assertThat(dto.message()).isNotNull();
            assertThat(dto.createdAt()).isNotNull();
            // read is a primitive boolean — always has a value
        }
    }

    /**
     * Propriedade 2: Listagem de não lidas filtra corretamente
     * Valida: Requisito 1.4
     */
    @Property(tries = 100)
    void listUnreadFiltersCorrectly(
            @ForAll("unreadNotificationLists") List<Notification> unreadNotifications
    ) {
        // Arrange — repository already returns only unread items
        when(notificationRepository.findAllUnread()).thenReturn(unreadNotifications);

        // Act
        List<NotificationResponseDTO> result = notificationService.listUnread();

        // Assert
        assertThat(result).allSatisfy(dto -> assertThat(dto.read()).isFalse());
    }

    /**
     * Propriedade 3: Criação de notificação persiste com read=false
     * Valida: Requisitos 2.1, 5.1
     */
    @Property(tries = 100)
    void createNotificationRoundTrip(
            @ForAll("validStockIds") UUID stockId,
            @ForAll("nonBlankMessages") String message
    ) {
        // Arrange
        Stock stock = Stock.create("Produto Teste", "Descrição", 10, BigDecimal.TEN, "Categoria", 5);

        when(stockRepository.findById(stockId)).thenReturn(Optional.of(stock));
        when(notificationRepository.save(any(Notification.class))).thenAnswer(invocation -> invocation.getArgument(0));

        NotificationRequestDTO request = new NotificationRequestDTO(stockId, message);

        // Act
        NotificationResponseDTO response = notificationService.send(request);

        // Assert
        assertThat(response).isNotNull();
        assertThat(response.read()).isFalse();
        assertThat(response.id()).isNull(); // id is generated by JPA, not set in-memory
        assertThat(response.stockId()).isEqualTo(stockId);
        assertThat(response.message()).isEqualTo(message);
    }

    /**
     * Propriedade 5: Marcar como lida é idempotente
     * Valida: Requisitos 3.1, 3.3
     */
    @Property(tries = 100)
    void markAsReadIsIdempotent(
            @ForAll("validStockIds") UUID id,
            @ForAll("callCounts") int times
    ) {
        // Arrange
        Notification notification = Notification.createStockAlert(UUID.randomUUID(), "Alerta de teste");
        when(notificationRepository.findById(id)).thenReturn(Optional.of(notification));
        when(notificationRepository.save(any(Notification.class))).thenAnswer(invocation -> invocation.getArgument(0));

        // Act & Assert — every call must result in read=true
        for (int i = 0; i < times; i++) {
            NotificationResponseDTO response = notificationService.markAsRead(id);
            assertThat(response.read())
                    .as("read deve ser true após a chamada %d de markAsRead()", i + 1)
                    .isTrue();
        }
    }

    /**
     * Propriedade 7: Timestamps são registrados na criação e atualizados na modificação
     * Valida: Requisitos 5.2, 5.3
     * Feature: notification-stock-monitor, Propriedade 7: timestampsAreSetCorrectly
     */
    @Property(tries = 100)
    void timestampsAreSetCorrectly(
            @ForAll("validStockIds") UUID stockId,
            @ForAll("nonBlankMessages") String message
    ) {
        // Act — create notification directly on domain object
        Notification notification = Notification.createStockAlert(stockId, message);

        // Assert — timestamps are non-null after creation
        assertThat(notification.getCreatedAt()).isNotNull();
        assertThat(notification.getUpdatedAt()).isNotNull();

        // Record updatedAt before markAsRead
        java.time.LocalDateTime updatedAtBefore = notification.getUpdatedAt();

        // Act — mark as read
        notification.markAsRead();

        // Assert — updatedAt after is >= updatedAt before
        assertThat(notification.getUpdatedAt())
                .as("updatedAt após markAsRead() deve ser >= updatedAt antes")
                .isAfterOrEqualTo(updatedAtBefore);
    }

    @Provide
    Arbitrary<UUID> validStockIds() {
        return Arbitraries.create(UUID::randomUUID);
    }

    @Provide
    Arbitrary<String> nonBlankMessages() {
        return Arbitraries.strings()
                .withCharRange('a', 'z')
                .ofMinLength(1)
                .ofMaxLength(100);
    }

    @Provide
    Arbitrary<Integer> callCounts() {
        return Arbitraries.integers().between(1, 5);
    }

    @Provide
    Arbitrary<List<Notification>> notificationLists() {
        Arbitrary<UUID> uuids = Arbitraries.create(UUID::randomUUID);
        Arbitrary<String> messages = Arbitraries.strings()
                .withCharRange('a', 'z')
                .ofMinLength(1)
                .ofMaxLength(50);
        Arbitrary<Notification> notificationArbitrary = Combinators.combine(uuids, messages)
                .as(Notification::createStockAlert);
        return notificationArbitrary.list().ofMinSize(0).ofMaxSize(10);
    }

    @Provide
    Arbitrary<List<Notification>> unreadNotificationLists() {
        // All generated notifications start with read=false (factory default)
        Arbitrary<UUID> uuids = Arbitraries.create(UUID::randomUUID);
        Arbitrary<String> messages = Arbitraries.strings()
                .withCharRange('a', 'z')
                .ofMinLength(1)
                .ofMaxLength(50);
        Arbitrary<Notification> notificationArbitrary = Combinators.combine(uuids, messages)
                .as(Notification::createStockAlert);
        return notificationArbitrary.list().ofMinSize(0).ofMaxSize(10);
    }
}
